---
- hosts: all

  gather_facts: no
  
  tasks:
  - name: copy file at root dir of flash in slot 3 of sw1(ios)
    routeros_command:
      commands: /tool fetch check-certificate=no url="{{url}}"
      
  - name: Get cert name
    set_fact:
      certname: "{{ url | regex_search('[^\/])*.jpg') }}"

  - name: Display resource statistics (routeros)
    routeros_command:
      commands: /system resource print
