---
- hosts: all

  gather_facts: no
  
  tasks:
  - name: copy file at root dir of flash in slot 3 of sw1(ios)
    routeros_command:
      commands: /tool fetch url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Text-txt.svg/64px-Text-txt.svg.png" mode=https

  - name: Display resource statistics (routeros)
    routeros_command:
      commands: /system resource print
