---
- hosts: all

  gather_facts: no
  ansible_network_os: routeros
  
  tasks:
  - name: copy file at root dir of flash in slot 3 of sw1(ios)
    net_put:
      src: /home/van/hi.txt
      protocol: sftp
      dest : /hi.txt
