---
- hosts: all

  gather_facts: no
    
#  tasks:
#  - name: Download cert file
#    routeros_command:
#      commands: /tool fetch check-certificate=no url="{{certurl}}"
      
#  - name: Download key file
#    routeros_command:
#      commands: /tool fetch check-certificate=no url="{{keyurl}}"
     
  - name: Export old cert
    routeros_command:
     commands: /ip hotspot profile export file=precert

  - name: Import new cert
    routeros_command:
      commands:
        - /certificate import file-name{{certname}} passphrase=1
        - /certificate print
        - /certificate import file-name{{keyname}} passphrase=1
        - /certificate print

  - name: Set Cert name and Fingerprint
    routeros_command:
      commands:
        - /certificate set [find fingerprint="{{fingerprint}}"] name={{certname}}
        - /certificate print

  - name: Set new certificate on all MT Server Profiles 
    routeros_command:
      commands: 
        - /ip hotspot profile set 0 ssl-certificate=none
        - /ip hotspot profile print

