---
- hosts: all

  gather_facts: no
    
  tasks:
  - name: copy file at root dir of flash in slot 3 of sw1(ios)
    routeros_command:
      commands: /tool fetch check-certificate=no url="{{url}}"
     
  - name: Import new cert
    routeros_command:
      commands:
        - /certificate import file-name={{certname}} passphrase=1
        - /certificate print
